[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
doc = false
doctest = false

[dev-dependencies]
fantoccini = "0.21.1"
serde_json = "1.0.127"
tokio = { version = "1", features = ["full"] }
